import cv2
import numpy as np
import matplotlib.pyplot as  plt



# img0 = cv2.imread('./7.jpg')
# #img0 = cv2.resize(img0, None,fx=0.25, fy=0.25)
# img1 = cv2.imread('./8.jpg')
# img2 = cv2.imread('./9.jpg')
# #img2 = cv2.resize(img2, None,fx=0.25, fy=0.25)
# img3 = cv2.imread('./10.jpg')
# #img3 = cv2.resize(img3, None,fx=0.25, fy=0.25)
# img4 = cv2.imread('./11.jpg')
# #img4 = cv2.resize(img4, None,fx=0.25, fy=0.25)
# img5 = cv2.imread('./12.jpg')
# #img5 = cv2.resize(img5, None,fx=0.25, fy=0.25)
# img6 = cv2.imread('./13.jpg')
# #img6 = cv2.resize(img6, None,fx=0.25, fy=0.25)
# img7 = cv2.imread('./14.jpg')
# #img7 = cv2.resize(img7, None,fx=0.25, fy=0.25)
# img8 = cv2.imread('./15.jpg')
# #img8 = cv2.resize(img8, None,fx=0.25, fy=0.25)
# img9 = cv2.imread('./16.jpg')
# #img9 = cv2.resize(img9, None,fx=0.25, fy=0.25)
# #
# plt.figure()
# plt.subplot(4,4,1)
# plt.imshow(img0)
# plt.subplot(4,4,2)
# plt.imshow(img1)
# plt.subplot(4,4,3)
# plt.imshow(img2)
# plt.subplot(4,4,4)
# plt.imshow(img3)
# plt.subplot(4,4,5)
# plt.imshow(img4)
# plt.subplot(4,4,6)
# plt.imshow(img5)
# plt.subplot(4,4,7)
# plt.imshow(img6)
# plt.subplot(4,4,8)
# plt.imshow(img7)
# plt.subplot(4,4,9)
# plt.imshow(img8)
# plt.subplot(4,4,10)
# plt.imshow(img9)

img = cv2.imread('./B.jpg')
height,width = img.shape[:2]
imgs = []
for h in range(3):
    for w in range(3):
        img_new= img[max(0,round(((h-0.3)*height)/3.0)):round(((h+1)*height)/3.0), max(0,round(((w-0.3)*width)/3.0)):round(((w+1)*width)/3.0)]
        #print(img_new.shape)
        imgs.append(img_new)
stitcher = cv2.createStitcher(False)
ax = plt.subplot(3,4,1)
ax.set_title('(0,0)')
plt.imshow(imgs[0])
ax = plt.subplot(3,4,2)
ax.set_title('(0,1)')
plt.imshow(imgs[1])
ax = plt.subplot(3,4,3)
ax.set_title('(0,2)')
plt.imshow(imgs[2])
ax = plt.subplot(3,4,4)
ax.set_title('(1,0)')
plt.imshow(imgs[3])
ax = plt.subplot(3,4,5)
ax.set_title('(1,1)')
plt.imshow(imgs[4])
ax = plt.subplot(3,4,6)
ax.set_title('(1,2)')
plt.imshow(imgs[5])
ax = plt.subplot(3,4,7)
ax.set_title('(2,0)')
plt.imshow(imgs[6])
ax = plt.subplot(3,4,8)
ax.set_title('(2,1)')
plt.imshow(imgs[7])
ax = plt.subplot(3,4,9)
ax.set_title('(2,2)')
plt.imshow(imgs[8])
ax = plt.subplot(3,4,10)
ax.set_title('original picture')
plt.imshow(img)


#plt.show()
result = stitcher.stitch(imgs)
# print('the error is :')
print(result[0])
# plt.subplot(4,4,11)
# plt.imshow(img10)
# plt.subplot(4,4,12)
# plt.imshow(result[1])
# plt.show()
cv2.imwrite('./out.jpg',cv2.resize(result[1],(img.shape[1],img.shape[0])))
ax = plt.subplot(3,4,11)
ax.set_title('stitched image')
plt.imshow(result[1])
plt.show()